create extension if not exists pgcrypto;
create table if not exists public.rooms(id bigint generated by default as identity primary key,name text not null,active boolean not null default true);
create table if not exists public.reservations(
 id uuid primary key default gen_random_uuid(),
 room_id bigint not null references public.rooms(id) on delete cascade,
 reservation_date date not null,start_time time not null,
 name text not null,email text not null,created_at timestamptz not null default now(),
 constraint reservations_room_slot_unique unique(room_id,reservation_date,start_time)
);
insert into public.rooms(id,name) values(1,'Sala 01') on conflict(id) do nothing;
alter table public.rooms enable row level security;
alter table public.reservations enable row level security;
create policy "read active rooms" on public.rooms for select using(active=true);
create policy "read reservations" on public.reservations for select using(true);
create policy "create reservations" on public.reservations for insert with check(length(trim(name))>=2 and position('@' in email)>1);
